[commands]
copy = ["c", "с", "ψ"]
paste = ["v", "м", "ω"]
interrupt = ["x", "ч", "χ"]
close_pane = ["q", "й", "a", ";"]
new_tab = ["t", "е", "τ"]
close_tab = ["w", "ц", "z", "ς"]
quit = ["Q", "Й", "A", ":"]
previous_tab = [",", "б"]
next_tab = [".", "ю"]
