[commands]
copy = ["c", "с", "ψ"]
paste = ["v", "м", "ω"]
interrupt = ["x", "ч", "χ"]
close_pane = ["q", "й", "a", ";"]
new_tab = ["t", "е", "τ"]
close_tab = ["w", "ц", "z", "ς"]
rename_tab = ["R", "К"]
rename_pane = ["E", "У"]
quit = ["Q", "Й", "A", ":", "X", "Ч", "Χ"]
previous_tab = [",", "б"]
next_tab = [".", "ю"]
